### ISSUE TITLE
Screen Rotation 

### ISSUE THREAD

**Issue by JackDaviesDesign** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#10]
I would like to use the AMOLED Touch in vertical screen orientation, however I get this error during compilation. Thanks for your help.

`Compilation error: call to 'LilyGo_AMOLED::setRotation' declared with attribute error: setRotation Method Not implemented`

**Comment by lewisxhe** [comment]
Added 1.91" and 2.41" rotation examples and functionality
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/tree/master/examples/LVGL_Rotation
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/tree/master/examples/TFT_eSPI_Sprite_Rotation
