### ISSUE TITLE
Deep sleep current is too high! Example on deep sleep usage?

### ISSUE THREAD

**Issue by VICLER** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#11]
How is 160uA in sleep mode achieved? Is there somewhere an example for that? With a LiPo battery in deep sleep mode, I get 2mA current, which is 12x more than expected. Low sleep current is critical for battery-powered applications, and 2mA is just not acceptable.

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/blob/45c0dd522328acd1d786b59a74a8e2325260cf58/examples/Factory/Factory.ino#L137

**Comment by VICLER** [comment]
@lewisxhe thanks! Now I have about 100uA in deep sleep. It is a bit high, but much better as previously.
