### ISSUE TITLE
GPIO connector is too small and more examples are required

### ISSUE THREAD

**Issue by Arielhh** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#13]
lilygo development team,
The T4S3 display looks great but: 
How do you expect us to connect to such small pins? The provided female connector should be attached to a dedicated PCN to which we can solder the wires. providing only the connector does not solve the problem.
Also, more examples are required. it is too complicated now to understand how to work with that board.

**Comment by lewisxhe** [comment]
The remaining GPIO number of esp32s3 cannot place a larger connector (2.54mm) on T4S3, so using 1.27mm spacing is the most reasonable choice.

Regarding examples, what do you need?

**Comment by Arielhh** [comment]
Yes, but it is very complicated to solder wires to the female connector. It was better to attache the supplied female connector to a small PCB that allows wires to be connected more easily

**Comment by lewisxhe** [comment]
Do you mean to use a 1.27mm to 2.54mm PCB and insert it as a shield on the T4S3?

**Comment by lewisxhe** [comment]
Okay, I will give your feedback. I think there should be no problem with this. I think it is more appropriate to use a PCB shield than a wire.

**Comment by Arielhh** [comment]
I agree. Many thanks.

**Comment by Arielhh** [comment]
Can you give a simple example using TFT_eSPI (not with Sprite)?

**Comment by lewisxhe** [comment]
Hi.
1.Which board are you using? 
 2. You said that after writing most of the examples, the screen is still black. Can you point out which examples?  
3. Examples other than the TFT_eSPI wizard cannot be used because TFT_eSP does not support QSPI interface screens.

**Comment by Arielhh** [comment]
I am using the T4-S3. After a long time trying I managed to upload all the example codes but they seems to be too complicated.
I understand now that TFT_eSPI doesn't support QSPI interface screens. Can you provide a simple example on how to upload an image to the screen or drawing one circle? 
Is that the optimal way of showing graphics on this board?

**Comment by lewisxhe** [comment]
Currently, I think the most appropriate way is to use the lvgl graphics framework. If you are not familiar with it, you can check out the lvgl documentation, which is very easy to use.

Of course, you can also use the TFT_eSP wizard.

**Comment by Arielhh** [comment]
Thanks

**Comment by lewisxhe** [comment]
T-Display-Long-Shield

![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22990954/9796d1f0-0881-4ba4-a60f-d24a563101da)

T-Display AMOLED No plans for now

**Comment by Arielhh** [comment]
is it possible to purchase the T-Display-Long-Shield?

**Comment by lewisxhe** [comment]
> Looks great :) is it possible to purchase the T-Display-Long-Shield? BTW: the pins in this shield are not aligned with the actual connector of the T-Display Long.

 ? Not right? Where are you referring to?

![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22990954/1024a812-3221-4234-aa71-9d2015f966ca)

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22990954/903559a3-a715-45e2-ae70-a54f724d854e)
T4-S3 shield is also completed today

**Comment by Arielhh** [comment]
> > Looks great :) is it possible to purchase the T-Display-Long-Shield? BTW: the pins in this shield are not aligned with the actual connector of the T-Display Long.
> 
> ? Not right? Where are you referring to?

Yes, now it is ok. From the last photo, it was not possible to see the male pins of the connector. 
When it will be possible to buy them?

**Comment by lewisxhe** [comment]
Still need to wait for some time

**Comment by Arielhh** [comment]
In the long version shouldn’t it be a female connector instead of the male
shows in the picture?

**Comment by rhcp4life** [comment]
Any updates on the long shield?

I just ordered a IDC ribbon connector like this: 
uxcell IDC Wire Flat Ribbon Cable FC/FC Female Connector A-Type 30Pins 1.27mm Pitch 20cm Length
https://www.amazon.com/dp/B07SN9CYCY?ref=ppx_yo2ov_dt_b_product_details&th=1

**Comment by lewisxhe** [comment]
Production has been arranged and will be available for purchase soon.

**Comment by Arielhh** [comment]
Great news, thanks.
