### ISSUE TITLE
AMOLED Touch display home button not working in v1.0.4.

### ISSUE THREAD

**Issue by vpsmedeiros** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#14]
The home button on the AMOLED Touch display was working fine on v1.0.2, but after the v1.0.4 release it no longer works.

I loaded up the factory example program to verify it wasn't an error in my own program.  It seems the amoled.setHomeButtonCallback() function itself is not working.

**Comment by lewisxhe** [comment]
Thanks for the feedback. Recently, changes were made to the dependent libraries, which caused the failure. It has now been fixed.

**Comment by vpsmedeiros** [comment]
It works. Thanks you very much.
