### ISSUE TITLE
Home Button Callback no longer works after updating to v1.0.4

### ISSUE THREAD

**Issue by dingrgh** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#15]
Device: LilyGo AMOLED T-Display S3 Touch (1.91-in screen)

After updating to v1.0.4 from v1.0.1, the amoled.setHomeButtonCallback([](void *ptr) callback no longer works when the Home button is touched.

It compiles without an error. But it just does not work anymore.

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/issues/14

**Comment by dingrgh** [comment]
Thank you. v1.0.5 has fixed this.

**Comment by dingrgh** [comment]
Thank you! 

I can confirm that v1.0.5 has fixed the problem.
