### ISSUE TITLE
Product Page says MicroPython, but where can I find examples?

### ISSUE THREAD

**Issue by ctschach** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#17]
So, the Product Page:

https://www.lilygo.cc/products/t4-s3

Mentions that development can be done in MicroPython.  Are there any examples? Especially on how to access the display. I do have a project I'm working on and this "big" screen would be perfect for it...

**Comment by lewisxhe** [comment]
There is no Micropython driver yet, it may be added later.
