### ISSUE TITLE
Question about settings

### ISSUE THREAD

**Issue by Skorpionm** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#19]
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/blob/f7c2c4f553876c574c86850bbdd1ee50ecdd0dfe/src/initSequence.cpp#L519C1-L524C66

where did you get the magical Swire settings for bv6804. there is no description of the FE00 section in the datasheet, you can add this document ?

**Comment by lewisxhe** [comment]
This is provided by the screen supplier and I can't provide you with any information.
