### ISSUE TITLE
Amoled Series Code Base Consolidation

### ISSUE THREAD

**Issue by nikthefix** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#2]
Hi Lewis.

I'm a huge fan of your work and the amazing range of Lilygo products. I bought them all!

Can I make a suggestion?

You have consolidated the Amoled boards code base but I think this is a bad idea. Using i2c auto-detect of board specific peripherals is way too complicated / error prone and unnecessary. I think most users would prefer a separate repo for each board. It's easier to see what's going on. For those who want to learn from your code I think it would be better to have device specific repos.

I contribute but would like to do more.

nik

**Comment by lewisxhe** [comment]
Hi @nikthefix , thank you for your opinion. As a member who mainly maintains the LilyGo repository (you can see that 99% of the LilyGo repositories are maintained by me), I need to waste a lot of time every day answering beginners' questions about how to install and use it. If I If you write it in the form of a library, beginners will rarely encounter problems, such as library dependencies, compilation errors, etc.

What I wrote is not complicated, and it is distinguished by screen size. I believe it will not be difficult for familiar people to understand. I mainly serve most novice users, and I hope you can understand.

Recently, LilyGo has launched a number of AMOLED screens. They are basically the same. I merged them together mainly for the convenience of maintenance and ease of use by novices.

I would be very happy if you could help us contribute and welcome any helpful PRs

**Comment by nikthefix** [comment]
Understood.

Thanks for the quick reply.

nik

**Comment by lewisxhe** [comment]
If there is no problem, then I will close this issue. If there is any problem, please reopen it.
