### ISSUE TITLE
3D file for case?

### ISSUE THREAD

**Issue by nicpottier** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#20]
The case for the S3-Amoled-Touch looks quite nice on the site. This wasn't available when I bought it. Do you have 3D files (STEP or otherwise) available so we can print these ourselves?

Thanks!

**Comment by lewisxhe** [comment]
A request has been made to LilyGo and will be added in the next few days

**Comment by lewisxhe** [comment]
already added

**Comment by nicpottier** [comment]
Wow, thank you, that's amazing! (also appreciate that these are in zip files vs 7z for the board)

Incredible response and support.
