### ISSUE TITLE
Screen tearing on the T-Display S3 AMOLED V1.0

### ISSUE THREAD

**Issue by diegomacario** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#21]
Hi! I wrote a little menu for my T-Display S3 AMOLED V1.0. It works great! You can see it in this video:

https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/8304271/14d6bcd9-5f91-4f10-b0fb-3595074df25f

What I wanted to ask here is if there is a way to eliminate the tearing I see when I update the boxes in the screen. You can see the tearing in the video above, but it's easier to see it in these screenshots:

<img width="1461" alt="tearing_1" src="https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/8304271/c8fc2001-8c48-49cf-bae2-2ac51e5bf72e">
<img width="1025" alt="tearing_2" src="https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/8304271/49f1f946-747a-495c-adfc-df988f68c657">

I'm using sprites and only updating the parts of the screen that change, but I still see tearing.

I also see the same problem in this example from Volos Projects that I modified so that the dial boxes periodically turn red:

<img width="930" alt="Screenshot 2024-02-19 at 1 06 22 PM" src="https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/8304271/4c703b0c-f1d8-4a0a-9a83-0c1842accdb2">
<img width="854" alt="Screenshot 2024-02-19 at 1 06 38 PM" src="https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/8304271/4b270d49-009b-4b07-8606-c11d1b129fc2">
<img width="847" alt="Screenshot 2024-02-19 at 1 06 53 PM" src="https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/8304271/3ce45e82-161d-447f-bc75-b63aebb7690f">

Is there anything I can do about this? Thank you for any advice!

**Comment by lewisxhe** [comment]
If the refresh speed is too fast, tearing can be clearly seen. Reduce the refresh speed, or use partial refresh, but partial refresh is limited to only allow even coordinate values, or use lvgl

**Comment by diegomacario** [comment]
Thanks for the reply @lewisxhe! When you say partial refresh, do you mean only updating the part of the screen that changed like this?

```
amoled->pushColors(boxXPos, boxYPos, boxWidth, boxHeight, (uint16_t *)boxSprite.getPointer());
```

Because that's what I'm currently doing, and I only call `amoled->pushColors` when the button is pressed. So in my `update` function I'm not calling it all the time. Is that what you mean with reducing the refresh speed i.e. not calling `amoled->pushColors` every frame?

Thanks for any information!

**Comment by lewisxhe** [comment]
Yes, I have no other better way to prevent screen tearing

**Comment by diegomacario** [comment]
Alright, I guess I just have to avoid having large parts of my user interface change colors suddenly.

The displays seems to have support for some form of V-Sync:

```
    // {0x44, {0x01, 0x66},        0x02}, //Set_Tear_Scanline
    // {0x35, {0x00},        0x00}, //TE ON
    // {0x34, {0x00},        0x00}, //TE OFF
    // {0x36, {0x00},        0x01}, //Scan Direction Control
```

But I'm not sure if that would work with QSPI.

**Comment by lewisxhe** [comment]
At present, I only know that RGB panels support TE configuration, but QSPI currently does not see how to configure it.

**Comment by diegomacario** [comment]
A fix for this bug was developed in this thread: https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED/issues/2

So I will close this one now. Thank you!
