### ISSUE TITLE
ADC: CONFLICT! driver_ng is not allowed to be used with the legacy driver

### ISSUE THREAD

**Issue by omadab** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#22]
Infinite loop on boot:
Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x29 (SPI_FAST_FLASH_BOOT)
Saved PC:0x403787f9
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x508
load:0x403c9700,len:0x4
load:0x403c9704,len:0xad0
load:0x403cc700,len:0x29d8
entry 0x403c9880
E (332) ADC: CONFLICT! driver_ng is not allowed to be used with the legacy driver

abort() was called at PC 0x4208b103 on core 0

Backtrace: 0x403781e2:0x3fceb200 0x4037ffb1:0x3fceb220 0x40385c49:0x3fceb240 0x4208b103:0x3fceb2c0 0x42056fba:0x3fceb2e0 0x403784eb:0x3fceb310 0x403cd856:0x3fceb340 0x403cdafe:0x3fceb380 0x403c98d5:0x3fceb4b0 0x40045c01:0x3fceb570 |<-CORRUPTED

**Comment by lewisxhe** [comment]
README ， https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series#4%EF%B8%8F%E2%83%A3-install-from-arduino-library-manager-recommended
[Arduino ESP32 V 2.0.5 or above and below V3.0](https://docs.espressif.com/projects/arduino-esp32/en/latest/)
