### ISSUE TITLE
T4-S3 3D PCB model - incomplete

### ISSUE THREAD

**Issue by pike2k** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#25]
The file here: dimensions/T4-S3-AMOLED-PCB-3D.7z is lacking many dimensions and features. Can you provide the full 3D model?

**Comment by lewisxhe** [comment]
Already updated to the latest version of 3D, please note it only has the parts you need for the shell design part

**Comment by pike2k** [comment]
I need more dimensions, since I plan to design an 'Expansion board' and it would help a lot to know for instance where the 2x15 pin connector is located on the PCB!

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22990954/e7cce8bd-d448-4d71-9734-39fc582c6ebd)
Isn't this up there?

**Comment by pike2k** [comment]
![t4 pcb kicad](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/471737/f4d45da6-6523-414f-8951-fd9b2a0d4c8d)
I use FreeCAD 0.21.2 and this is all I get from T4-S3-AMOLED-PCB-3D.step

**Comment by lewisxhe** [comment]
All right . I put it in the wrong directory. it's OK now

**Comment by Serhii-Khramenkov** [comment]
> ![image](https://private-user-images.githubusercontent.com/22990954/317092748-e7cce8bd-d448-4d71-9734-39fc582c6ebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTQzNDAsIm5iZiI6MTcyMjk1NDA0MCwicGF0aCI6Ii8yMjk5MDk1NC8zMTcwOTI3NDgtZTdjY2U4YmQtZDQ0OC00ZDcxLTk3MzQtMzlmYzU4MmM2ZWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE0MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlM2M0MmFiNDQ4ZTM4NTZhZjc3NWZlNDcwN2U3NzM2ZWIzNDg4ZmZhZGYxNTNmNmNiYTAwODE1MzA2MTk1ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VSL9fvxNvlzUsD115wb3sYfz_YfqIpolRVdSfD1DMJA) Isn't this up there?

It's 2x16 pins connector on the photo, the same is in 3D model. There is 2x15 connectors on my version of display. Could You please clarify the situation ? Are there different versions ?

**Comment by pike2k** [comment]
I am designing a breadboard adapter for this product and I just got a big scare. In the Step file you provide, the pinheader is 2x16 pins. In reality it is 2x15 pins. Could you please fix it and position it where it should be on the PCB?

**Comment by lewisxhe** [comment]
Already updated
