### ISSUE TITLE
Wifi is very weak on t4 S3

### ISSUE THREAD

**Issue by isthaison** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#26]
T4 s3 and wifi signal is too bad. with signal capabilities that it can achieve

```
#include "WiFi.h"
void setup()
{
    Serial.begin(115200);
    bool err = false;

    WiFi.mode(WIFI_STA);

    Serial.println();
    Serial.println("******************************************************");
 


    WiFi.begin("SO95", "12345678");

    while (WiFi.status() != WL_CONNECTED)
    {
        delay(500);
        Serial.print(".");
    }

    Serial.println("WiFi Connected.");

    Serial.print("IP Address: ");
    Serial.println(WiFi.localIP());
    Serial.print("RSSI: ");
    Serial.println(WiFi.RSSI());
}

void loop()
{
    // put your main code here, to run repeatedly:
    Serial.print("RSSI: ");
    Serial.println(WiFi.RSSI());
   

    delay(1000);
}
```
RSSI: -64 while both devices are almost in contact with each other

**Comment by isthaison** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22739578/3f33fe45-2b22-4aa1-b6a2-96d2b9881e1f

**Comment by lewisxhe** [comment]
Take a photo of the back of the board and the wifi antenna part to see

**Comment by isthaison** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22739578/c4c42231-2910-4f78-89d4-1a53f94b0b42)

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22990954/509b8d28-9370-4c6a-8b7e-c65846e94ff9)
There should be two resistors here, right?

**Comment by isthaison** [comment]
I just kept the board original for testing. You can test directly with your version.

**Comment by lewisxhe** [comment]
The test results here will not be very bad. It is about 6 meters away from the router. There is a glass block in the middle. The signal is around -60. Can you remove the PCB on the back for testing?

**Comment by isthaison** [comment]
![23BF6E69-4B65-4CB6-B815-E7B7DE65128E](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22739578/957cb620-efd7-47e8-9024-7c899d4dde4e)
Can you help me get in touch with Skype, I'll video call you directly.

**Comment by lewisxhe** [comment]
sorry, we do not have that . This kind of problem cannot be solved remotely.

**Comment by isthaison** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22739578/2c917b33-a041-49a2-a665-ffe5a069b8f2

**Comment by isthaison** [comment]
I have found a problem on the board

**Comment by isthaison** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22739578/0d240026-95e0-49f2-861b-d62a82c4d364)![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22739578/27c3c598-7479-4b65-92a9-5d9dc0fcc8b8)![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22739578/c1007790-1254-4754-813d-7273bf4281e0)
#I had replace and repaired all antennas  achieved 7x rssi instead of 9x before

**Comment by isthaison** [comment]
For the signal line from the expansion antenna transmitted to the esp32, you installed a missing resistor. It caused the expansion antenna to not work. This is a serious error if the board is placed in a metal shell. then the built-in antennas on the board will not well work. In addition, the antennas integrated on the board have poor signal capture performance. You should consult about hardware design from the creator of the esp32 chip. How did they design the esp32 module?![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22739578/45189be7-a078-4ad3-94c6-99bee5e0bd19)

**Comment by lewisxhe** [comment]
Maybe you are a special case, the signal in my hand is not that bad.

**Comment by isthaison** [comment]
I have a suggestion, you try to operate it continuously for 24 hours then check the results again

**Comment by lewisxhe** [comment]
After three days of testing, the signal was kept at about - 65 dBM when the distance from the router was about 6 to 7 meters. Maybe you are an exception.

**Comment by lewisxhe** [comment]
If you have any other questions later, please contact your dealer.
