### ISSUE TITLE
T4-S3 On/Off switch does nothing

### ISSUE THREAD

**Issue by GSGDaren** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#27]
Quick question.  Is the toggle On/Off switch supposed to turn off the T4-S3?  Or, maybe its a software controlled switch?

I have a T4-S3 that is working very well (demos all work, etc) except the switch does nothing.  Defective?

**Comment by GSGDaren** [comment]
Think I may have found the issue.  The On/Off switch seems to only control battery power.  USB power is not interrupted by this switch.

Correct?

**Comment by lewisxhe** [comment]
YES,Juas Battery Switch

**Comment by GSGDaren** [comment]
Thanks Lewis!
