### ISSUE TITLE
Turning OFF the OLED screen

### ISSUE THREAD

**Issue by Arielhh** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#29]
As this is OLED screen which is susceptible to burn-in is there a way to turn off the OLED Screen and turning it back on by using the touch screen as a trigger?

**Comment by lewisxhe** [comment]
Just adjust the brightness to 0, and the AMOLED can be completely turned off

**Comment by Arielhh** [comment]
OK, great, thanks :)
