### ISSUE TITLE
Use of header to power the T4-S3 2.4 inch board with 5V

### ISSUE THREAD

**Issue by scuba-hacker** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#3]
The schematic shows pins 1/2 are connected to VBUS. VBUS is also connected to the USB-C power pins.

With USB-C not connected, can you please confirm whether or not it is safe to power the board with 5V connected to pin 1 of the header?

**Comment by lewisxhe** [comment]
Of course, when USBC is not connected, you can directly connect 5V to the 5v pin
