### ISSUE TITLE
Two finger touch patterns cause loss of touch response

### ISSUE THREAD

**Issue by Minorplanets76** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#34]
I have found that two finger gestures such as pinch cause the touch functionality to stop working.  I confirmed this with LVGL_rotation example as supplied, but has been an issue with my own ui's I have created.  Once a two finger event has happened there seems to be no way recover other than reboot.  Needs to ignore unsupported gestures or have a way to break from the scenario.

I have done further testing and have found the T4 Amoled is working fine with the same program, so it only seems to apply to the S3 V2 Amoled with touch.  Touch functionality still works as I can get touch coordinates after the ui functionality freezes.

**Comment by lewisxhe** [comment]
I used the LVGL_Rotation example and ran it on T4 -S3, AMOLED - 1.91 and did not find this problem

**Comment by Minorplanets76** [comment]
Hi, thanks for the prompt response.  I tried with a brand new board and found the same issue.  I have the T-Display S3 board with touch.  To replicate issue, I load rotation example, push the set rotation button to confirm touch is working.  Touch with one finger at top of screen (not touching buttons) and at same time swipe upwards with thumb.  Buttons are no longer responsive and have reboot.  I can do a video to demonstrate if you'd like.
![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/107326485/1968b94a-0d2a-4fa7-a142-470953567814)
It seems like it enters a state or event from which it never exits.

**Comment by lewisxhe** [comment]
I can't test the problem, it would be better if you could attach a video.

**Comment by Minorplanets76** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/107326485/3bc9581c-77b1-4f87-ac0e-724f4cbc7ba7

**Comment by lewisxhe** [comment]
From the video content, it seems that lvgl is frozen, but the touch response is still normal. It can be ruled out that the problem is caused by touch. I need time to investigate.

**Comment by lewisxhe** [comment]
The touch driver has been updated. You can test it. I did not find this problem in my test here. You should be using platformio, right?

**Comment by vpsmedeiros** [comment]
I had the same issue with the touch screen becoming unresponsive, but I did not know why or when it would happen.  I just replicated the issue by pinching the screen while pressing a touch screen button.

Initial test with your latest revision seems to have fixed my issue.  Thanks!

**Comment by Minorplanets76** [comment]
Yes that appears to have fixed the issue.  Thanks
