### ISSUE TITLE
Replacement screen for T4-S3

### ISSUE THREAD

**Issue by richgain** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#35]
![IMG_1863](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/1440566/938b12a7-4d1b-4d5d-9bd7-3305d859387b)
![IMG_1862](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/1440566/481c0c3a-dc4c-407c-a646-2eb76142295c)
I accidentally dropped my T4-S3 whilst trying to fit it into the 3D printed shell. 
It still works fine but a greenish patch has appeared in the top-left corner of the screen (see pictures).

Is it possible to get a screen replacement?  I have already ordered another device as I love the form factor, but I would like to restore this one to full working order if possible.

**Comment by lewisxhe** [comment]
Contact the seller and explain the situation to him.
