### ISSUE TITLE
Location of external psram component

### ISSUE THREAD

**Issue by amir1387aht** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#36]
Can somebody show me which component is psram?

**Comment by StevenLCox** [comment]
The ESP32S3 R8 has the 8MB PSRAM built into it's package. Basically it's a multichip module. So no external RAM on the LilyGo PCB is needed. Take a look at the ESP32S3 dataset page 10. There is an external flash chip on the PCB.
-Steve

**Comment by amir1387aht** [comment]
> The ESP32S3 R8 has the 8MB PSRAM built into it's package. Basically it's a multichip module. So no external RAM on the LilyGo PCB is needed. Take a look at the ESP32S3 dataset page 10. There is an external flash chip on the PCB. -Steve

Thank you!

**Comment by amir1387aht** [comment]
> The ESP32S3 R8 has the 8MB PSRAM built into it's package. Basically it's a multichip module. So no external RAM on the LilyGo PCB is needed. Take a look at the ESP32S3 dataset page 10. There is an external flash chip on the PCB. -Steve

And a question, it is possible to add more psram?

**Comment by StevenLCox** [comment]
I guess there are two ways to add more RAM. Looking at the ESP32S3 datasheet there is the ESP32-S3R16V version that has 16MB of in-package PSRAM. You could also make your own board with an SPI or QPI PSRAM chip like this [](https://www.adafruit.com/product/4677). 

Also maybe something like this: [https://machdyne.com/product/qqspi-psram32/](url), [https://github.com/machdyne/qqspi](url). (I haven't looked at these in any detail but am guessing that the ESP32S3 could support them. Not sure how they would fit into the memory map.)

**Comment by amir1387aht** [comment]
>  I guess there are two ways to add more RAM. Looking at the ESP32S3 datasheet there is the ESP32-S3R16V version that has 16MB of in-package PSRAM. You could also make your own board with an SPI or QPI PSRAM chip like this [](https://www.adafruit.com/product/4677). 
> 
> Also maybe something like this: [https://machdyne.com/product/qqspi-psram32/](url), [https://github.com/machdyne/qqspi](url). (I haven't looked at these in any detail but am guessing that the ESP32S3 could support them. Not sure how they would fit into the memory map.)

Thanks!
