### ISSUE TITLE
Missing RM690B0 datasheet for 2.4 inch amoled board

### ISSUE THREAD

**Issue by scuba-hacker** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#4]
Please add datasheet RM690B0 for the 2.4 inch amoled board to the datasheets directory.

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/blob/master/datasheet/RM690B0%20DataSheet_V0.2.pdf

**Comment by scuba-hacker** [comment]
Excellent, thank you!
