### ISSUE TITLE
Using the IPEX antenna connector

### ISSUE THREAD

**Issue by radioralph** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#40]
I wish to use an external antenna with the T-Display S3 AMOLED. Is the IPEX socket connected, or do resistors/capacitors need to be inserted or removed?

**Comment by isthaison** [comment]
@
![image_2024_05_13T03_30_04_255Z](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22739578/03d87b5c-e90c-405c-9cab-0470532bb37f)
I also saw this same thing 2 months ago

**Comment by radioralph** [comment]
Thank you @isthaison for your observation regarding the antenna connector on the T4-S3 board. The schematic diagram for the T-Display-S3 suggests that some components will need to be added to enable the IPEX connector, and some components will need to be removed to disable the on-board 3D antenna. The resistors noted are 0R, but the cap values (if required) are not mentioned.

If I am correct in my understanding, the question becomes: what are the recommended values and placement locations of the added/removed components?

Best regards,

**Comment by isthaison** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/assets/22739578/6b21818e-e7e8-4652-9d22-70daed05868d)

**Comment by radioralph** [comment]
Thank you @isthaison - that looks straightforward. I will let you know how it goes.
Many thanks again.

**Comment by isthaison** [comment]
@radioralph  Is it Ok?
