### ISSUE TITLE
t s3 amoled v2 

### ISSUE THREAD

**Issue by asg02fever** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#43]
hi, 
i have the amoled board that as been sent for content creation by your team but sadly i cant make screen work with firmware that was made on v1, the lvgl example work pretty good but the way to make the screen work in code line is way different than normal esp32 and its also really harder i dont understand a think there firmware was youtube counter by roblatour

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/issues/41
