### ISSUE TITLE
Issue with T-display amoled V2. Not black screen or not full power off.

### ISSUE THREAD

**Issue by fermintm** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#48]
Apparently these modules do not turn off the screen completely or leave it black. In the dark you can see that they are lit with a red tone and therefore consume more battery. I have 2 modules and both have the same error.
I have tried with several libraries and examples and the same error occurs.
I don't know if it is from the LilyGo_AMOLED library or it is a general problem.

Video link: https://youtu.be/pqQM53qh8_A

**Comment by lewisxhe** [comment]
AMOLED normally has no light after adjusting the brightness to 0. Try adjusting the brightness to 0 directly.
```
amoled.setBrightness(0)
```

**Comment by fermintm** [comment]
> AMOLED normally has no light after adjusting the brightness to 0. Try adjusting the brightness to 0 directly.
> 
> ```
> amoled.setBrightness(0)
> ```

View link of my video. The issue is with latest Lilygo amoled Library.
