### ISSUE TITLE
isBatteryConnect always returns false

### ISSUE THREAD

**Issue by MikeyMoMo** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#49]
On T4S3: 

```
if (amoled.isBatteryConnect())
    Serial.println("Battery Connected");
  else
    Serial.println("Battery NOT Connected");
```

always says NOT connected.  Battery is 18650 connected normally and working normally.  It powers the unit just fine without external input power.

**Comment by lewisxhe** [comment]
T4 S3 This method is invalid
