### ISSUE TITLE
TFT_eSprite example fails for 2.4 inch board

### ISSUE THREAD

**Issue by scuba-hacker** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#5]
gImage_true_color isn't a large enough array to represent all pixels for the 450 x 600 screen, so subsequently when the array is passed to spr.pushImage in line 89 with the WIDTH and HEIGHT of the board there is a crash and restart.

There needs to be either an alternative array for the 2.4 inch board or, as I did, the code for showing the image needs disabling for this board.

**Comment by lewisxhe** [comment]
oh ! Yes . The initial example is provided for use with 1.47. It will be compatible with several other models later, which may cause errors. Thank you for your feedback.

**Comment by scuba-hacker** [comment]
You’re welcome.
