### ISSUE TITLE
Typo in LilyGo_AMOLED.h

### ISSUE THREAD

**Issue by MikeyMoMo** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#51]
Line 337 of LilyGo_AMOLED.h has this problem:

` const BoardsConfigure_t *getBoarsdConfigure();`
 
 Maybe it does not affect anything at all but would be nice if it was spelled to match the rest of the code.
 
 Apparently, someone noticed and copied the error.  Here are lines 541 & 542 in factory,ino, gui.cpp
 
```
//SDCard
const  BoardsConfigure_t *boards = amoled.getBoarsdConfigure();
```

Please correct both before this goes any farther afield.

**Comment by lewisxhe** [comment]
The typo has been corrected some time ago.
