### ISSUE TITLE
T4-S3-2.41 - blinking red LED

### ISSUE THREAD

**Issue by regha** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#52]
Hi,
After uploading a program (GFX_HelloWorld) with Arduino IDE, nothing appears on th screen and red led is blinking (about 5 times a second)...
What can I do ?...

**Comment by lewisxhe** [comment]
What about other examples? Testing factory firmware?

**Comment by OhioJoe** [comment]
Did you press the Reset (rst) button after uploading?

**Comment by carbuthn** [comment]
The T4 display is very nice but the flashing red led makes it un-useable for me. I wanted to buy a lot more but the led prevents that.

**Comment by lewisxhe** [comment]
LED can be turned off [PPM_Example](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/blob/f88802d283480d835f9ef3ac9495d7854a575b27/examples/PPM_Example/PPM_Example.ino#L70)

**Comment by carbuthn** [comment]
Is there a way to turn it off in esphome?

**Comment by bernie26262** [comment]
So helpful. Thanks a lot for this info.
