### ISSUE TITLE
PlatformIO does not support .INO files?

### ISSUE THREAD

**Issue by pike2k** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#60]
PlatformIO Core 6.1.16·Home 3.4.4

Building in release mode
Compiling .pio\build\T-Display-AMOLED\src\Touchpad.ino.cpp.o
Building .pio\build\T-Display-AMOLED\bootloader.bin
Generating partitions .pio\build\T-Display-AMOLED\partitions.bin
xtensa-esp32s3-elf-g++: error: examples/Touchpad/Touchpad.ino.cpp: No such file or directory
xtensa-esp32s3-elf-g++: fatal error: no input files
compilation terminated.

**Comment by lewisxhe** [comment]
Please uninstall platformio and reinstall it. This is a problem caused by incomplete installation.

**Comment by pike2k** [comment]
Thanks! That did the trick
