### ISSUE TITLE
T4-S3 GPIO18 is not free to use!

### ISSUE THREAD

**Issue by Katana1234** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#61]
Hi,

looking at the schematic GPIO18 looks like to be a pin that can be used freely:
![image](https://github.com/user-attachments/assets/ce20ac80-2baf-44c6-8b75-a426d2201119)

When in reality it is connected to the display.
![image](https://github.com/user-attachments/assets/fe9091ff-7b5c-4a1f-8786-7a0023468de3)

Why can't this be seen in the schematic???
I fried one of my displays because i thought it was an unused pin!

**Comment by lewisxhe** [comment]
It was added to TEPin later, but the schematic was not updated. Is your screen damaged?

**Comment by Katana1234** [comment]
> It was added to TEPin later, but the schematic was not updated. Is your screen damaged?

yes it is. i was using it for an analog reading, but due to the fact that it was connected to the display it drew a very high current until the board or the screen broke...

**Comment by lewisxhe** [comment]
Please contact customer service and I will arrange to send you another one.

**Comment by lewisxhe** [comment]
Schematic updated, issue closed
