### ISSUE TITLE
connect SIM800L to T-Display S3 Amoled (or t-display s3 Long)

### ISSUE THREAD

**Issue by zorro1011** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#67]
hello everyone
can i connect and use the SIM800L module to the T-Display S3 Amoled or T-displey S3 long?
i am not sure if it can be done using the TX RX pins

thanks
best regards
zorro

**Comment by lewisxhe** [comment]
UART interface refer to this, any GPIO can be set as UART
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/blob/e33ecc035731502e99f0b86d7d19af1fc75da8f1/examples/QWIIC_GPS_Shield/QWIIC_GPS_Shield.ino#L30

**Comment by zorro1011** [comment]
I was afraid there could be conflicts with the display or touch management.

thanks so much
