### ISSUE TITLE
PlatformIO and UnknownEnvNamesError: Unknown environment names 'src_dir = examples/Factory'. Valid names are 'T-Display-AMOLED, T-Display-AMOLED-191-ArduinoGFX'

### ISSUE THREAD

**Issue by dtswk** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#69]
I am very new to platformIO so suspect I might be doing something wrong.

I have downloaded the code, placed it in Projects \ LilyGo-AMOLED-Series-master.

Edited the PlatformIO.ini for examples/Factory and clicked complie and upload and I get the following error

UnknownEnvNamesError: Unknown environment names 'src_dir = examples/Factory'. Valid names are 'T-Display-AMOLED, T-Display-AMOLED-191-ArduinoGFX'

I also tried a number of the other examples and all the same.

Any suggestions?

Matt

**Comment by lewisxhe** [comment]
After downloading the project, just open platformio.ini and select a line src_dir = xxxx and remove the ; in front of it. Then keep the ; in front of other src_dir = xxxx to compile. By default, default_envs does not need to be edited.
![image](https://github.com/user-attachments/assets/a67c09cd-1021-4231-aabc-7576f9659879)
