### ISSUE TITLE
Document example devices that can attach to the T4 S3 2x15 connector

### ISSUE THREAD

**Issue by HowdyMoto** [Xinyuan-LilyGO/LilyGo-AMOLED-Series#8]
I'd love to know how to set this up as a camera shield without soldering a mess of wires to the pins, for example.

**Comment by lewisxhe** [comment]
There is no camera shield available for T4S3, it is only available in 1.91 currently.

**Comment by lewisxhe** [comment]
If you still have any problems, please reopen
